### ISSUE TITLE
Auto switching button

### ISSUE THREAD

**Issue by jmb** [gasolinehorse/not-by-ai#1]
I'm not sure if this is helpful, but I wanted to make the button automatically switch between light and dark themes. I have modified the SVG to do this for the "written by" button and added it to the footer of my website. When in dark mode the CSS class `dark` is added to the documentRoot and triggers the black background version, with the whit background being shown otherwise. I've also added a `<title>` for accessibility.

[written-by-human-not-by-ai-auto.svg](https://user-images.githubusercontent.com/110238/226059325-1a7b9c7d-05a6-4b9a-b2c6-b4bebe88d821.svg)

Happy to modify the other two SVGs and submit a PR if this is something that would be useful.

**Comment by gasolinehorse** [comment]
This is brilliant. I have added accessibility improvement to the to-do list. Regarding light and dark themes, for now, I would like to leave it as something the users adjust themselves as the badges are meant to serve as a barebone graphic that can be as versatile and customizable as possible to support everyone's needs. I appreciate the idea and will rethink it if we get more requests for it in the future.

That said, you are certainly more than welcome to submit a PR with the added <title> (but without the emoji in it due to inconsistent rendering) for all badges. Otherwise, I will take it on!
